config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'gamesets#index'
  resources :gamesets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gameset.rb
class Gameset < ApplicationRecord
  validates :name, :img, :ref, presence: true
  validates :ref, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/gamesets_controller.rb
require 'open-uri'

class GamesetsController < ApplicationController
  before_action :find_gameset, only: [:show, :destroy]
  skip_before_action :authenticate_user!, only: :index
  def index
    @gamesets = Gameset.all
  end

  def show
  end

  def new
    @gameset = Gameset.new
  end

  def create
    @gameset = Gameset.new(gameset_params)
    url = "https://brickset.com//api/v3.asmx/getSets?apiKey=3-qokZ-lzv7-6HvfX&userHash=gXue3LT9UC&params={'setNumber':'#{@gameset.ref}'}"
    lego = JSON.parse(open(url).read)
    render :new and return if lego["sets"].empty?

    @gameset.name = lego["sets"].first["name"]
    @gameset.img = lego["sets"].first["image"]["imageURL"]
    if @gameset.save
      redirect_to gamesets_path
    else
      render :new
    end
  end

  def destroy
    @gameset.destroy
    redirect_to gamesets_path
  end

  private

  def find_gameset
    @gameset = Gameset.find(params[:id])
  end

  def gameset_params
    params.require(:gameset).permit(:ref)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gamesets/index.html.erb
<h1>Nos Legos !</h1>
<hr>
<br>
<% if current_user %>
  <%= link_to 'add new set', new_gameset_path %>
<% end %>

<div class="container">
  <div class="cards">
    <% @gamesets.each do |gameset| %>
      <div class="card">
        <div class="img" style="background-image: url(<%="#{gameset.img}"%>)"></div>
        <div class="body">
          <span><%= gameset.name %></span>
          <span><%= gameset.ref %></span>
        </div>
        <div class="footer">
          <p><%= (link_to 'delete', gameset_path(gameset), method:'delete', data: {confirm: "are you sure?"}) if current_user %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/gamesets/new.html.erb
<h1>Gamesets#new</h1>
<p>Find me in app/views/gamesets/new.html.erb</p>

<div class="container">
  <%= render 'shared/form' %>
</div>

app/views/gamesets/show.html.erb
<h1>Gamesets#show</h1>
<p>Find me in app/views/gamesets/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLego</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_form.html.erb
<p>si le formulaire ne passe pas c'est que l'app ne trouve pas le set</p>
<p>ne pas oublier le numéro de sous-modele (s'il n'y en a pas sur la boite, essayer '1'</p>
<p>exemple : 75192-1 pour le faucon millenium</p>
<%= simple_form_for(@gameset) do |f| %>
  <%= f.input :ref %>
  <%= f.button :submit, class:'btn btn-primary' %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to gamesets_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>